### ISSUE TITLE
Download button on "live data vs time" leads to 404

### ISSUE THREAD

**Issue by jangevaa** [DougEdey/SB_Elsinore_Server#50]
Download all data results in a 404

**Comment by DougEdey** [comment]
I cannot reproduce this, please check for any error messages in the main elsinore (serverside) logs.

**Comment by jangevaa** [comment]
This is what I've got going on /controller (I've pulled your recent changes)

```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://10.0.1.33:8088/nls/messages_en_CA.properties?_=1425252044486Failed to load resource: the server responded with a status of 404 (Not Found)
http://10.0.1.33:8088/nls/messages_en.properties?_=1425252057891Failed to load resource: the server responded with a status of 404 (Not Found)
http://10.0.1.33:8088/nls/messages_en_CA.properties?_=1425252057892Failed to load resource: the server responded with a status of 404 (Not Found)
```

And on /graph

```
[Error] TypeError: undefined is not an object (evaluating 'series["axis"]["y"]')
	onDataReceived (graph, line 50)
	j (jquery.js, line 2)
	fireWith (jquery.js, line 2)
	x (jquery.js, line 4)
	(anonymous function) (jquery.js, line 4)
[Error] TypeError: undefined is not an object (evaluating 'series["axis"]["y"]')
	onDataReceived (graph, line 50)
	j (jquery.js, line 2)
	fireWith (jquery.js, line 2)
	x (jquery.js, line 4)
	(anonymous function) (jquery.js, line 4)
```

**Comment by DougEdey** [comment]
I specifically said the serer side logs. i.e. the ones on the raspberryPi/BBB

**Comment by jangevaa** [comment]
Sorry Doug. 

Seems to work when starting via `sudo ./launch.sh`, but not when ran as a background process. 

Upon start up:
```
root@beaglebone:~/beta_sb# sudo ./launch.sh -p 8088 -c brewery.cfg
Starting Elsinore as root
Mar 01, 2015 11:30:54 PM com.sb.elsinore.LaunchControl main
INFO: Running Brewery Controller.
Mar 01, 2015 11:30:55 PM com.sb.elsinore.LaunchControl readConfig
INFO: CFG IS NULL
Mar 01, 2015 11:30:55 PM com.sb.elsinore.LaunchControl enableRecorder
INFO: Enabling the recorder
[Fatal Error] :1:1: Premature end of file.
Could not parse lshw output
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:347)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at jGPIO.DTO.autoDetectSystemFile(DTO.java:176)
	at jGPIO.DTO.findDetails(DTO.java:338)
	at jGPIO.GPIO.getPinNumber(GPIO.java:138)
	at jGPIO.GPIO.<init>(GPIO.java:102)
	at jGPIO.OutPin.<init>(OutPin.java:16)
	at com.sb.elsinore.Switch.<init>(Switch.java:54)
	at com.sb.elsinore.LaunchControl.parseSwitches(LaunchControl.java:926)
	at com.sb.elsinore.LaunchControl.parseXMLSections(LaunchControl.java:2281)
	at com.sb.elsinore.LaunchControl.readConfig(LaunchControl.java:737)
	at com.sb.elsinore.LaunchControl.<init>(LaunchControl.java:428)
	at com.sb.elsinore.LaunchControl.main(LaunchControl.java:313)
No definitions file found, assuming direct mapping
[Fatal Error] :1:1: Premature end of file.
Could not parse lshw output
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:347)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at jGPIO.DTO.autoDetectSystemFile(DTO.java:176)
	at jGPIO.DTO.findDetails(DTO.java:338)
	at jGPIO.GPIO.getPinNumber(GPIO.java:138)
	at jGPIO.GPIO.<init>(GPIO.java:102)
	at jGPIO.OutPin.<init>(OutPin.java:16)
	at com.sb.elsinore.Switch.<init>(Switch.java:54)
	at com.sb.elsinore.LaunchControl.parseSwitches(LaunchControl.java:926)
	at com.sb.elsinore.LaunchControl.parseXMLSections(LaunchControl.java:2281)
	at com.sb.elsinore.LaunchControl.readConfig(LaunchControl.java:737)
	at com.sb.elsinore.LaunchControl.<init>(LaunchControl.java:428)
	at com.sb.elsinore.LaunchControl.main(LaunchControl.java:313)
No definitions file found, assuming direct mapping
Mar 01, 2015 11:30:55 PM com.sb.elsinore.LaunchControl parseXMLSections
INFO: Checking section general
Mar 01, 2015 11:30:55 PM com.sb.elsinore.LaunchControl parseXMLSections
INFO: Checking section switches
Mar 01, 2015 11:30:55 PM com.sb.elsinore.LaunchControl parseXMLSections
INFO: Checking section phSensors
Mar 01, 2015 11:30:55 PM com.sb.elsinore.LaunchControl parseXMLSections
INFO: Checking section device
Mar 01, 2015 11:30:55 PM com.sb.elsinore.LaunchControl parseDevice
INFO: Parsing XML Device: Hot_Liquor_Tank
Mar 01, 2015 11:30:55 PM com.sb.elsinore.LaunchControl parseDevice
INFO: Not enough volume data points, 0 found
Mar 01, 2015 11:30:55 PM com.sb.elsinore.Temp <init>
INFO: Adding28-000005ab3caf
Mar 01, 2015 11:30:55 PM com.sb.elsinore.Temp <init>
INFO: 28-000005ab3caf added.
Mar 01, 2015 11:30:55 PM com.sb.elsinore.LaunchControl startDevice
INFO: Adding Hot_Liquor_Tank GPIO is (GPIO2_3)
Mar 01, 2015 11:30:55 PM com.sb.elsinore.Temp setScale
WARNING: Cut off is: -999
Mar 01, 2015 11:30:55 PM com.sb.elsinore.Temp setScale
WARNING: Cut off is now: -999
Mar 01, 2015 11:30:55 PM com.sb.elsinore.LaunchControl startDevice
INFO: Adding PID with GPIO: GPIO2_3
Mar 01, 2015 11:30:55 PM com.sb.elsinore.Temp updateTempFromFile
WARNING: Couldn't find the device under: /sys/bus/w1/devices/28-000005ab3caf/w1_slave
Mar 01, 2015 11:30:55 PM com.sb.elsinore.PID detectGPIO
INFO: Matches: 3
Mar 01, 2015 11:30:55 PM com.sb.elsinore.PID detectGPIO
INFO: Matched GPIO pinout for Beagleboard: GPIO2_3. OS: null
Mar 01, 2015 11:30:55 PM com.sb.elsinore.PID run
INFO: Running Hot_Liquor_Tank PID.
[Fatal Error] :1:1: Premature end of file.
Could not parse lshw output
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:347)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at jGPIO.DTO.autoDetectSystemFile(DTO.java:176)
	at jGPIO.DTO.findDetails(DTO.java:338)
	at jGPIO.GPIO.getPinNumber(GPIO.java:138)
	at com.sb.elsinore.LaunchControl.parseDevice(LaunchControl.java:2542)
	at com.sb.elsinore.LaunchControl.parseXMLSections(LaunchControl.java:2293)
	at com.sb.elsinore.LaunchControl.readConfig(LaunchControl.java:737)
	at com.sb.elsinore.LaunchControl.<init>(LaunchControl.java:428)
	at com.sb.elsinore.LaunchControl.main(LaunchControl.java:313)
No definitions file found, assuming direct mapping
Invalid options when setting up Hysteria: Min value is less than the max value
Mar 01, 2015 11:30:56 PM com.sb.elsinore.PID updateValues
INFO: 0: 0: 0
Mar 01, 2015 11:30:56 PM com.sb.elsinore.PID updateValues
INFO: 40: 0: 30
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl savePID
INFO: Saving the information for Hot_Liquor_Tank
[Fatal Error] :1:1: Premature end of file.
Could not parse lshw output
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:347)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at jGPIO.DTO.autoDetectSystemFile(DTO.java:176)
	at jGPIO.DTO.findDetails(DTO.java:338)
	at jGPIO.GPIO.getPinNumber(GPIO.java:138)
	at jGPIO.GPIO.<init>(GPIO.java:102)
	at jGPIO.OutPin.<init>(OutPin.java:16)
	at com.sb.elsinore.devices.OutputDevice.initializeSSR(OutputDevice.java:65)
	at com.sb.elsinore.devices.OutputDevice.<init>(OutputDevice.java:43)
	at com.sb.elsinore.OutputControl.<init>(OutputControl.java:42)
	at com.sb.elsinore.PID.run(PID.java:212)
	at java.lang.Thread.run(Thread.java:745)
No definitions file found, assuming direct mapping
Mar 01, 2015 11:30:56 PM com.sb.elsinore.OutputControl run
INFO: Fduty: 0
Mar 01, 2015 11:30:56 PM com.sb.elsinore.OutputControl run
INFO: Fduty: 0
Mar 01, 2015 11:30:56 PM com.sb.elsinore.PID run
INFO: off: Hot_Liquor_Tank status: 0E-52 duty cycle: 0
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl savePID
INFO: Using base node device with ID Hot_Liquor_Tank
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of heat
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on device
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of cycle_time
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on heat
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of proportional
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on heat
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of integral
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on heat
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of derivative
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on heat
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of gpio
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on heat
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of invert
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on heat
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of cool
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on device
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of cycle_time
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on cool
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of delay
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on cool
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of proportional
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on cool
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of integral
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on cool
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of derivative
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on cool
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of gpio
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on cool
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of invert
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on cool
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl parseXMLSections
INFO: Checking section device
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl parseDevice
INFO: Parsing XML Device: Boil_Kettle
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl parseDevice
INFO: Not enough volume data points, 0 found
Mar 01, 2015 11:30:56 PM com.sb.elsinore.Temp <init>
INFO: Adding28-000005aa8de3
Mar 01, 2015 11:30:56 PM com.sb.elsinore.Temp <init>
INFO: 28-000005aa8de3 added.
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl startDevice
INFO: Adding Boil_Kettle GPIO is (GPIO2_4)
Mar 01, 2015 11:30:56 PM com.sb.elsinore.Temp setScale
WARNING: Cut off is: -999
Mar 01, 2015 11:30:56 PM com.sb.elsinore.Temp setScale
WARNING: Cut off is now: -999
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl startDevice
INFO: Adding PID with GPIO: GPIO2_4
Mar 01, 2015 11:30:56 PM com.sb.elsinore.PID detectGPIO
INFO: Matches: 3
Mar 01, 2015 11:30:56 PM com.sb.elsinore.PID detectGPIO
INFO: Matched GPIO pinout for Beagleboard: GPIO2_4. OS: null
Mar 01, 2015 11:30:56 PM com.sb.elsinore.PID run
INFO: Running Boil_Kettle PID.
[Fatal Error] :1:1: Premature end of file.
Could not parse lshw output
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:347)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at jGPIO.DTO.autoDetectSystemFile(DTO.java:176)
	at jGPIO.DTO.findDetails(DTO.java:338)
	at jGPIO.GPIO.getPinNumber(GPIO.java:138)
	at com.sb.elsinore.LaunchControl.parseDevice(LaunchControl.java:2542)
	at com.sb.elsinore.LaunchControl.parseXMLSections(LaunchControl.java:2293)
	at com.sb.elsinore.LaunchControl.readConfig(LaunchControl.java:737)
	at com.sb.elsinore.LaunchControl.<init>(LaunchControl.java:428)
	at com.sb.elsinore.LaunchControl.main(LaunchControl.java:313)
No definitions file found, assuming direct mapping
Invalid options when setting up Hysteria: Min value is less than the max value
[Fatal Error] :1:1: Premature end of file.
Could not parse lshw output
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:347)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at jGPIO.DTO.autoDetectSystemFile(DTO.java:176)
	at jGPIO.DTO.findDetails(DTO.java:338)
	at jGPIO.GPIO.getPinNumber(GPIO.java:138)
	at jGPIO.GPIO.<init>(GPIO.java:102)
	at jGPIO.OutPin.<init>(OutPin.java:16)
	at com.sb.elsinore.devices.OutputDevice.initializeSSR(OutputDevice.java:65)
	at com.sb.elsinore.devices.OutputDevice.<init>(OutputDevice.java:43)
	at com.sb.elsinore.OutputControl.<init>(OutputControl.java:42)
	at com.sb.elsinore.PID.run(PID.java:212)
	at java.lang.Thread.run(Thread.java:745)
Mar 01, 2015 11:30:56 PM com.sb.elsinore.PID updateValues
INFO: 0: 0: 0
No definitions file found, assuming direct mapping
Mar 01, 2015 11:30:56 PM com.sb.elsinore.PID updateValues
INFO: 36: 0: 90
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl savePID
INFO: Saving the information for Boil_Kettle
Mar 01, 2015 11:30:56 PM com.sb.elsinore.PID run
INFO: off: Boil_Kettle status: 0E-52 duty cycle: 0
Mar 01, 2015 11:30:56 PM com.sb.elsinore.OutputControl run
INFO: Fduty: 0
Mar 01, 2015 11:30:56 PM com.sb.elsinore.OutputControl run
INFO: Fduty: 0
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl savePID
INFO: Using base node device with ID Boil_Kettle
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of heat
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on device
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of cycle_time
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on heat
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of proportional
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on heat
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of integral
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on heat
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of derivative
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on heat
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of gpio
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on heat
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of invert
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on heat
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of cool
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on device
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of cycle_time
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on cool
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of delay
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on cool
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of proportional
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on cool
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of integral
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on cool
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of derivative
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on cool
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of gpio
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on cool
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of invert
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on cool
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl parseXMLSections
INFO: Checking section device
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl parseDevice
INFO: Parsing XML Device: Keg_fridge
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl parseDevice
INFO: Not enough volume data points, 0 found
Mar 01, 2015 11:30:56 PM com.sb.elsinore.Temp <init>
INFO: Adding28-00043b696dff
Mar 01, 2015 11:30:56 PM com.sb.elsinore.Temp <init>
INFO: 28-00043b696dff added.
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl startDevice
INFO: Adding Keg_fridge GPIO is (GPIO1_12)
Mar 01, 2015 11:30:56 PM com.sb.elsinore.Temp setScale
WARNING: Cut off is: -999
Mar 01, 2015 11:30:56 PM com.sb.elsinore.Temp setScale
WARNING: Cut off is now: -999
Mar 01, 2015 11:30:56 PM com.sb.elsinore.LaunchControl startDevice
INFO: Adding PID with GPIO: GPIO1_12
Mar 01, 2015 11:30:56 PM com.sb.elsinore.PID detectGPIO
INFO: Matches: 3
Mar 01, 2015 11:30:56 PM com.sb.elsinore.PID detectGPIO
INFO: Matched GPIO pinout for Beagleboard: GPIO1_12. OS: null
Mar 01, 2015 11:30:56 PM com.sb.elsinore.PID run
INFO: Running Keg_fridge PID.
[Fatal Error] :1:1: Premature end of file.
Could not parse lshw output
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:347)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at jGPIO.DTO.autoDetectSystemFile(DTO.java:176)
	at jGPIO.DTO.findDetails(DTO.java:338)
	at jGPIO.GPIO.getPinNumber(GPIO.java:138)
	at com.sb.elsinore.LaunchControl.parseDevice(LaunchControl.java:2542)
	at com.sb.elsinore.LaunchControl.parseXMLSections(LaunchControl.java:2293)
	at com.sb.elsinore.LaunchControl.readConfig(LaunchControl.java:737)
	at com.sb.elsinore.LaunchControl.<init>(LaunchControl.java:428)
	at com.sb.elsinore.LaunchControl.main(LaunchControl.java:313)
[Fatal Error] :1:1: Premature end of file.
Could not parse lshw output
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)No definitions file found, assuming direct mapping

	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:347)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at jGPIO.DTO.autoDetectSystemFile(DTO.java:176)
	at jGPIO.DTO.findDetails(DTO.java:338)
	at jGPIO.GPIO.getPinNumber(GPIO.java:138)
	at jGPIO.GPIO.<init>(GPIO.java:102)
	at jGPIO.OutPin.<init>(OutPin.java:16)
	at com.sb.elsinore.devices.OutputDevice.initializeSSR(OutputDevice.java:65)
	at com.sb.elsinore.devices.OutputDevice.<init>(OutputDevice.java:43)
	at com.sb.elsinore.OutputControl.<init>(OutputControl.java:42)
	at com.sb.elsinore.PID.run(PID.java:212)
	at java.lang.Thread.run(Thread.java:745)
No definitions file found, assuming direct mappingMar 01, 2015 11:30:57 PM com.sb.elsinore.PID updateValues
INFO: 0: 0: 0

Mar 01, 2015 11:30:57 PM com.sb.elsinore.PID updateValues
INFO: 0: 0: 0
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl savePID
INFO: Saving the information for Keg_fridge
Mar 01, 2015 11:30:57 PM com.sb.elsinore.OutputControl run
INFO: Fduty: 0
Mar 01, 2015 11:30:57 PM com.sb.elsinore.PID run
INFO: off: Keg_fridge status: 0E-52 duty cycle: 0
Mar 01, 2015 11:30:57 PM com.sb.elsinore.OutputControl run
INFO: Fduty: 0
Mar 01, 2015 11:30:57 PM com.sb.elsinore.OutputControl run
INFO: Fduty: 0
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl savePID
INFO: Using base node device with ID Keg_fridge
Mar 01, 2015 11:30:57 PM com.sb.elsinore.OutputControl run
INFO: Fduty: 0
Mar 01, 2015 11:30:57 PM com.sb.elsinore.PID run
INFO: off: Hot_Liquor_Tank status: 0.00 duty cycle: 0
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of heat
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on device
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of cycle_time
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on heat
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of proportional
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on heat
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of integral
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on heat
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of derivative
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on heat
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of gpio
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on heat
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of invert
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on heat
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of cool
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on device
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of cycle_time
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on cool
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of delay
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on cool
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of proportional
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on cool
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of integral
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on cool
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of derivative
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on cool
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of gpio
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on cool
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: Creating element of invert
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl addNewElement
INFO: on cool
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl parseXMLSections
INFO: Checking section device
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl parseDevice
INFO: Parsing XML Device: Mash_Tun
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl parseDevice
INFO: Not enough volume data points, 0 found
Mar 01, 2015 11:30:57 PM com.sb.elsinore.Temp <init>
INFO: Adding28-000005aba55d
Mar 01, 2015 11:30:57 PM com.sb.elsinore.Temp <init>
INFO: 28-000005aba55d added.
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl startDevice
INFO: Adding Mash_Tun GPIO is (null)
Mar 01, 2015 11:30:57 PM com.sb.elsinore.Temp setScale
WARNING: Cut off is: -999
Mar 01, 2015 11:30:57 PM com.sb.elsinore.Temp setScale
WARNING: Cut off is now: -999
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl <init>
INFO: Starting Status Recorder
Mar 01, 2015 11:30:57 PM com.sb.elsinore.LaunchControl <init>
INFO: CONFIG READ COMPLETED***********
Mar 01, 2015 11:30:57 PM com.sb.elsinore.BrewServer <init>
INFO: Launching on port 8088
Mar 01, 2015 11:30:57 PM com.sb.elsinore.BrewServer <init>
INFO: Enabled logging at level:WARNING
```

**Comment by DougEdey** [comment]
Fixed, issue is due to not writing to the correct directory.
