### ISSUE TITLE
Strange data logging/graphing behaviour after latest commits

### ISSUE THREAD

**Issue by jangevaa** [DougEdey/SB_Elsinore_Server#53]
Hmm. Graphs don't appear at all for some probes. For others there are data points which haven't been observed, and new data points are being added to the middle rather than to the end of the the time series. I feel like this is somewhat of an ambiguous description, so let me know if I can give you more info!

![erraticgraphs](https://cloud.githubusercontent.com/assets/5422422/6455713/fe3b774a-c125-11e4-8ada-31227a59279d.png)

**Comment by jangevaa** [comment]
This may only be an issue when running as a service, let me get more information for you.

**Comment by jangevaa** [comment]
Er, suddently having difficulty recreating... I should probably get whatever's going on my BBB sorted before doing too much more beta testing. Sorry about this one.

**Comment by jangevaa** [comment]
Sorry to reopen this, but some strange things happening. Data logging doesn't appear to be occurring at all. Any graphs that may show up seem to be based off some previous measurements (previous logs?). When logs are manually deleted, and sb elsinore is restarted, no graphs are generated/shown at all.

**Comment by DougEdey** [comment]
Try pulling the latest beta, and are there any logs (from the terminal on the server) when you see the issue?

**Comment by jangevaa** [comment]
Latest beta: Graphs actually appear, but all with a scale of 0 to 1, and without any data loading on them.
Data is once again being saved to the graph-data directory (which I hadn't experienced before the last commit).

Upon stopping SB, I get this (I feel like I would've noticed this earlier... but anyways):

```
java.io.FileNotFoundException: /sys/class/gpio/gpio44/value (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at java.io.FileInputStream.<init>(FileInputStream.java:101)
	at java.io.FileReader.<init>(FileReader.java:58)
	at jGPIO.GPIO.readFile(GPIO.java:183)
	at jGPIO.GPIO.readValue(GPIO.java:204)
	at jGPIO.OutPin.getValue(OutPin.java:48)
	at com.sb.elsinore.Switch.getStatus(Switch.java:71)
	at com.sb.elsinore.LaunchControl.getJSONStatus(LaunchControl.java:675)
	at com.sb.elsinore.StatusRecorder.run(StatusRecorder.java:107)
	at java.lang.Thread.run(Thread.java:745)
java.io.FileNotFoundException: /sys/class/gpio/gpio26/value (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at java.io.FileInputStream.<init>(FileInputStream.java:101)
	at java.io.FileReader.<init>(FileReader.java:58)
	at jGPIO.GPIO.readFile(GPIO.java:183)
	at jGPIO.GPIO.readValue(GPIO.java:204)
	at jGPIO.OutPin.getValue(OutPin.java:48)
	at com.sb.elsinore.Switch.getStatus(Switch.java:71)
	at com.sb.elsinore.LaunchControl.getJSONStatus(LaunchControl.java:675)
	at com.sb.elsinore.StatusRecorder.run(StatusRecorder.java:107)
	at java.lang.Thread.run(Thread.java:745)
```

In an attempt to be of some utility I checked out 8 commits since first noticing issues to see if I could pin-point when my issues started... and surprisingly confirmed data logging and plotting worked correctly in all of them (basically everything up until the latest commit). Given this, I'm quite convinced that my intermittent issues are not due to a change in your code but likely something going wrong with my system.

Would an error be thrown if the graph-data directory somehow became corrupted or unwritable for some reason (by writing data for 6 probes at once could I prone these kinds of errors)? More likely though I think my real issue is firmware or hardware related, especially since you picked up on the whole `lshw` thing.

**Comment by DougEdey** [comment]
I think the issue was because of some bad logic that created multiple status recorders, bad data paths, and so on.

I believe I recreated your issue and you should find it's OK now. Please try the latest Beta builds.

**Comment by jangevaa** [comment]
Very interesting, I will give a shot later tonight. Thank you.

**Comment by jangevaa** [comment]
All working well after last commit! No error messages on close or strange graphing behaviour.
